# Generated by Django 2.2.4 on 2019-10-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omikuji', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omikuji_items',
            name='omikuji_id',
        ),
        migrations.AddField(
            model_name='omikuji_items',
            name='omikuji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='omikuji.Omikuji'),
        ),
    ]
