# Generated by Django 2.2.4 on 2019-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquormap', '0002_auto_20190911_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
